### ISSUE TITLE
Could not parse Browserslist result to a meaningful format. entry=safari TP

### ISSUE THREAD

**Issue by jroru** [nihalgonsalves/esbuild-plugin-browserslist#128]
The following browserslist query:

```
  "last 3 Chrome major versions",
  "last 3 Safari major versions",
  "unreleased Chrome versions",
  "unreleased Safari versions"
```

Resolves to include:

```
...
safari TP
```

Which then is logged by `esbuild-plugin-browserslist`:

```
Could not parse Browserslist result to a meaningful format. entry=safari TP
``` 

The equivalent browsers for chrome do not cause `esbuild-plugin-browserslist` to emit such a log.

I believe that `esbuild-plugin-browserslist` should be updated to resolve this browser version into an esbuild target.

Thanks!

**Comment by nihalgonsalves** [comment]
Thanks for the report! I took a look, but am not sure what we _should_ do with Safari TP. It's a floating target - right now that would mean an esbuild target of `safari17`, but that would be `safari17.1` or so next month when Safari 17 is stable.

I could add a special case to not log an error and ignore it, but it wouldn't change the behaviour. What target would you expect from that query?

If it's just about the error, you could also change the query to add `not safari TP`: https://browsersl.ist/#q=last+3+Chrome+major+versions%2C%0Alast+3+Safari+major+versions%2C%0Aunreleased+Chrome+versions%2C%0Aunreleased+Safari+versions%2C%0Anot+safari+TP

This still returns 17, which is what Safari TP currently is, but avoids the floating `TP` version.

**Comment by jroru** [comment]
Thanks for looking into this!

> What target would you expect from that query?

If this is my browserslist query in entirety:
```
  "unreleased Safari versions"
```

I believe `esbuild-plugin-browserslist ` should resolve it to the esbuild target `safari17`.

I do not know how and when it should change to `safari17.1`, but I believe that it should.

I think Browserslist has made this difficult by resolving to `safari TP` rather than e.g. `safari 17`

**Comment by jroru** [comment]
> If it's just about the error, you could also change the query to add not safari TP

In my case, I do explicitly wish to support unreleased Safari versions (TP)
