### ISSUE TITLE
allow newer versions of esbuild

### ISSUE THREAD

**Issue by dwhieb** [nihalgonsalves/esbuild-plugin-browserslist#19]
Attempting to use this plugin with newer versions of esbuild (v0.14) throws a package version error during install.

Could the package's version of esbuild be set to allow newer versions: `^0.13.0` instead of `~0.13.0`?

https://github.com/nihalgonsalves/esbuild-plugin-browserslist/blob/48ae8975360fdf1bba99cb5973dae3ba347f326f/package.json#L46

If not, could the esbuild version used in this package be bumped to v0.14?

**Comment by nihalgonsalves** [comment]
Thanks for the report @dwhieb! I published a new version with updated peerdeps here: https://github.com/nihalgonsalves/esbuild-plugin-browserslist/releases/tag/v0.4.0

About why it's set to `~0.x`: esbuild follows pre-v1 semver, i.e. minor releases can cause breaking changes, so I'd rather leave it like this for now.

Resolved by #20

**Comment by dwhieb** [comment]
@nihalgonsalves thanks very much! I figured that was the case, so I appreciate the update. 🙏🏼
