### ISSUE TITLE
[Question] Can I load browserslist from config file?

### ISSUE THREAD

**Issue by kingyue737** [nihalgonsalves/esbuild-plugin-browserslist#58]
Can I load browserslist config in either `package.json` or the `.browserslistrc` via `resolveToEsbuildTarget`?

**Comment by nihalgonsalves** [comment]
Hey @kingyue737, this plugin uses the Browserslist [JS API](https://github.com/browserslist/browserslist#js-api) so I believe if you just use pass the result of running `browserslist()` without a query it should use the config file as described in the browserslist README.
